[versions]
#####
# SDK Versions
#####
sdk-compile = "35"
sdk-min = "26"
sdk-target = "33"
#####
# Library Versions
#####
androidx-activity-compose = "1.9.3"
androidx-appcompat = "1.7.0"
androidx-core-ktx = "1.15.0"
androidx-compose-bom = "2024.12.01" # developer.android.com/develop/ui/compose/bom/bom-mapping
androidx-constraintLayout-compose = "1.1.0"
androidx-lifecycle = "2.8.7"
androidx-navigation = "2.8.5"
androidx-paging = "3.3.5"
androidx-room = "2.6.1"
androidx-test-espresso = "3.6.1"
androidx-test-ext-junit = "1.2.1"
google-android-material = "1.12.0"
junit = "4.13.2"
kotlin-coroutines = "1.10.1"
squareup-moshi = "1.15.2"
squareup-retrofit = "2.9.0"
squareup-okhttp = "4.12.0"
#####
# Plugin Versions
#####
kotlin = "2.0.21"
gradle = "8.7.3"
ksp = "2.0.21-1.0.27"

[libraries]
# Android
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidx-navigation" }
google-android-material = { group = "com.google.android.material", name = "material", version.ref = "google-android-material" }
# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-toolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
androidx-constraintLayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "androidx-constraintLayout-compose" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidx-paging" }
# Compose-Debug
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
# Networking
squareup-retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "squareup-retrofit" }
squareup-retrofit2-converterGson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "squareup-retrofit" }
squareup-retrofit2-converterMoshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "squareup-retrofit" }
squareup-okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "squareup-okhttp" }
squareup-moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "squareup-moshi" }
squareup-moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "squareup-moshi" }
# Room
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "androidx-room" }
# Testing-Unit
junit = { group = "junit", name = "junit", version.ref = "junit" }
jetbrains-kotlinx-coroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
# Testing - Android
androidx-compose-ui-testJunit = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidx-navigation" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }

[bundles]
android = [
    "androidx-activity-compose", "androidx-appcompat", "androidx-core-ktx",
    "androidx-lifecycle-runtime-ktx", "androidx-navigation", "google-android-material"
]
compose = [
    "androidx-compose-material-icons", "androidx-compose-material3", "androidx-compose-ui",
    "androidx-compose-ui-toolingPreview", "androidx-navigation-compose", "androidx-constraintLayout-compose",
    "androidx-paging-compose"
]
compose-debug = [
    "androidx-compose-ui-testManifest", "androidx-compose-ui-tooling", "squareup-retrofit2-converterMoshi",
    "squareup-okhttp-logging", "squareup-moshi", "squareup-moshi-kotlin"
]
networking = [
    "squareup-retrofit2-retrofit", "squareup-retrofit2-converterGson"
]
room = [
    "androidx-room-ktx", "androidx-room-runtime", "androidx-room-paging"
]
testing-unit = [
    "junit", "jetbrains-kotlinx-coroutinesTest"
]
testing-android = [
    "androidx-compose-ui-testJunit", "androidx-navigation-testing", "androidx-test-espresso",
    "androidx-test-ext-junit"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
