plugins {
    alias libs.plugins.android.application
    alias libs.plugins.jetbrains.kotlin.android
    alias libs.plugins.compose.compiler
    id 'kotlin-kapt'
}

android {
    namespace 'com.astrick.sandbox.app'
    /**
     * compileSdk specifies the Android API level Gradle should use to
     * compile your app. This means your app can use the API features included in
     * this API level and lower.
     */
    compileSdk libs.versions.sdk.compile.get().toInteger()

    /**
     * The defaultConfig block encapsulates default settings and entries for all
     * build variants and can override some attributes in main/AndroidManifest.xml
     * dynamically from the build system. You can configure product flavors to override
     * these values for different versions of your app.
     */
    defaultConfig {
        // Also known as package name
        applicationId "com.astrick.sandbox"
        // Defines the minimum API level required to run the app.
        minSdk libs.versions.sdk.min.get().toInteger()
        /**
         * The target SDK version is the version of the Android framework that your app is
         * specifically developed and tested against.
         * Indicates the highest Android version that your app is designed to be compatible with.
         * Allows your app to use new features and behaviors introduced in that version in runtime.
          */
        targetSdk libs.versions.sdk.target.get().toInteger()
        /**
         * Version code is an int so the system knows which versions are newer
         */
        versionCode 1
        /**
         * Version Name is the human readable version of the version code.
         * This is what will appear on the PlayStore etc
         */
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        compose true
        viewBinding true
    }
}

dependencies {

    // Android
    implementation(libs.bundles.android)

    // Compose
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.bundles.compose)
    debugImplementation(libs.bundles.compose.debug)

    // Room
    implementation(libs.bundles.room)
    kapt(libs.androidx.room.compiler)

    // Network
    implementation(libs.bundles.networking)

    // Testing
    testImplementation(libs.bundles.testing.unit)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.bundles.testing.android)

}
